console.log(Math.round(4.6));
console.log(Math.ceil(4.9));
console.log(Math.floor(-4.2));
console.log(Math.trunc(4.4));
console.log(Math.sign(0));
console.log(Math.pow(8, 2));
console.log(Math.sqrt(64));
console.log(Math.abs(-4.7));
console.log(Math.sin(90 * Math.PI / 180));
console.log(Math.min(0, 150, 30, 20, -8, -200));
console.log(Math.log(1));
